import { useEffect, useMemo, useState } from "react";

type Props = {
  command: string;
  open: boolean;
  onClose: () => void;
  onCopied?: () => void;
};

export default function CopyCommandModal({ command, open, onClose, onCopied }: Props) {
  const [ack, setAck] = useState(false);
  const canCopy = useMemo(() => ack && command.trim().length > 0, [ack, command]);

  useEffect(() => {
    if (!open) {
      setAck(false);
    }
  }, [open]);

  if (!open) {
    return null;
  }

  async function doCopy() {
    if (!canCopy) {
      return;
    }
    await navigator.clipboard.writeText(command);
    onCopied?.();
    onClose();
  }

  return (
    <div className="modalOverlay" role="dialog" aria-modal="true">
      <div className="modal">
        <h3>⚠️ Review Suggested Command</h3>
        <div className="code">{command}</div>
        <div className="banner" style={{ marginTop: 10 }}>
          This command is generated by AI and may be harmful. Do NOT run blindly.
        </div>
        <label className="row" style={{ marginTop: 10 }}>
          <input
            type="checkbox"
            checked={ack}
            onChange={(e) => setAck(e.target.checked)}
            aria-label="ack"
          />
          <span>I have verified this in a test environment</span>
        </label>
        <div className="row" style={{ justifyContent: "flex-end", marginTop: 10 }}>
          <button className="btn secondary" onClick={onClose}>
            Cancel
          </button>
          <button className="btn" onClick={doCopy} disabled={!canCopy}>
            Copy to Clipboard
          </button>
        </div>
      </div>
    </div>
  );
}

